site_title: Katalon Docs
site_domain: docs.katalon.com
site_url: https://docs.katalon.com
site_icon: /images/katalon/template/favicon.png
site_twitter: https://twitter.com/katalon_studio
site_twitter_mention: katalon_studio
github_editme_path: katalon-studio/docs

staging: true

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  toc_levels: 2..3

incremental: false

compress_images:
  images_path: "images/**/*.{gif,png,jpg,jpeg,svg}"

plugins:
  - jekyll-redirect-from
  - jekyll-compress-images

# algia index
algolia:
  application_id: 5E7YZB1TD0
  index_name: docs
  search_only_api_key: fbbaaba34cbd44a2dca3bf899eff9cec
  indexing_batch_size: 10
  max_record_size: 10000
  files_to_exclude:
    - "_site/**/*"

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "docs"
      comments: true
      search: true
      topnav: topnav
